<a href="https://colab.research.google.com/github/ksandeep18/MachineLearning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. What are NumPy arrays?
# NumPy arrays are homogeneous multidimensional arrays. This means they store elements of the same data type (e.g., integers, floats) in a grid-like structure. They are the foundation of numerical computing in Python and are much more efficient than standard Python lists for numerical operations due to vectorization.

# 2. Key Features of NumPy Arrays
# - Homogeneity: All elements are of the same data type.
# - Multidimensionality: Can be 1D, 2D, 3D, and so on.
# - Vectorization: Operations are applied to entire arrays at once, eliminating explicit loops in many cases, leading to performance gains.
# - Broadcasting: Allows operations between arrays of different shapes under certain conditions, automatically expanding smaller arrays to match larger ones.
# - Efficient storage: Stores data contiguously in memory, leading to faster access and manipulation.

# 3. Creating NumPy Arrays
# Various methods exist to create NumPy arrays:
# - From lists: np.array([1, 2, 3])
# - Using arange: np.arange(start, stop, step) to create sequences.
# - Using zeros and ones: np.zeros((rows, cols)), np.ones((rows, cols)).
# - Using random number generation: np.random.rand(), np.random.randn(), etc.

# 4. Array Attributes
# - shape: Dimensions of the array (tuple).
# - size: Total number of elements.
# - dtype: Data type of the elements.

# 5. Array Operations
# - Arithmetic operations: Element-wise addition, subtraction, multiplication, division.
# - Matrix multiplication: np.dot(array1, array2) or array1 @ array2.
# - Aggregation functions: sum(), mean(), std(), max(), min().

# 6. Indexing and Slicing
# - Access individual elements: array[index].
# - Extract portions of arrays: array[start:stop:step].
# - Boolean indexing: Select elements based on a condition (e.g., array[array > 5]).

# 7. Reshaping and Broadcasting
# - reshape(): Changes the dimensions of the array without altering the data.
# - Broadcasting:  Allows arithmetic operations on arrays of different shapes under specific rules.


# 8. NumPy Modules for Advanced Operations
# - np.linalg: Linear algebra functions (matrix inversion, determinants, eigenvalues).
# - np.fft: Fast Fourier Transform.
# - np.polynomial: Polynomial operations.


# Example illustrating key concepts
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
my_matrix = np.array([[1, 2], [3, 4]])

print("Original array:", my_array)
print("Shape:", my_array.shape)
print("Reshaped:", my_array.reshape(5, 1))  # Reshaping
print("Mean:", np.mean(my_array))         # Aggregation
print("Matrix:\n", my_matrix)
print("Matrix multiplication:\n", np.dot(my_matrix, my_matrix)) # Matrix Multiplication

#Boolean Indexing
bool_idx = (my_array > 2)
print(my_array[bool_idx]) # elements greater than 2


In [1]:
import numpy as np

# Creating NumPy arrays
# From a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("Array from list:", my_array)

# Using arange
array_arange = np.arange(0, 10, 2)  # Start, stop, step
print("Array using arange:", array_arange)

# Multi-dimensional arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)


# Array attributes
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)


# Array operations
# Arithmetic operations (element-wise)
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)  # Element-wise
print("Division:", array1 / array2)

# Matrix multiplication
matrix_product = np.dot(matrix, array1)  # or matrix @ array1
print("Matrix product:\n", matrix_product)


# Indexing and slicing
print("Element at index 2:", my_array[2])
print("Slice from index 1 to 3:", my_array[1:4])

# Boolean indexing
boolean_index = my_array > 2
print("Boolean indexing:", my_array[boolean_index])

# Reshaping arrays
reshaped_array = my_array.reshape(1, 5)  # Change dimensions
print("Reshaped array:\n", reshaped_array)

# Aggregation functions
print("Sum:", np.sum(my_array))
print("Mean:", np.mean(my_array))
print("Standard deviation:", np.std(my_array))
print("Max:", np.max(my_array))
print("Min:", np.min(my_array))


# Broadcasting
# NumPy allows operations between arrays of different shapes if they can be expanded to match.
array3 = np.array([1, 2, 3])
scalar = 2
print("Broadcasting:", array3 + scalar)  # Adds 2 to each element


# Useful functions
# Random number generation
random_array = np.random.rand(3, 3)
print("Random array:\n", random_array)

# zeros, ones
zeros_array = np.zeros((2, 3))
print("Zeros array:\n", zeros_array)

ones_array = np.ones((2, 3))
print("Ones array:\n", ones_array)


# Linear algebra
# Eigenvalues and eigenvectors, matrix inversion, etc.
# (np.linalg module)

# More specialized functions for data science
# (np.fft for signal processing, np.polynomial for polynomials, etc.)


Array from list: [1 2 3 4 5]
Array using arange: [0 2 4 6 8]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int64
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Matrix product:
 [14 32 50]
Element at index 2: 3
Slice from index 1 to 3: [2 3 4]
Boolean indexing: [3 4 5]
Reshaped array:
 [[1 2 3 4 5]]
Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951
Max: 5
Min: 1
Broadcasting: [3 4 5]
Random array:
 [[0.22480749 0.55230394 0.02129245]
 [0.9542291  0.64242173 0.32817726]
 [0.56216139 0.88230609 0.64049478]]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
